### ISSUE TITLE
Introduce viewdoc?

### ISSUE THREAD

**Issue by creasty** [creasty/dotfiles#51]
https://github.com/powerman/vim-plugin-viewdoc

```toml
[[plugins]]
repo = 'powerman/vim-plugin-viewdoc'
on_cmd = ['ViewDocMan']
```

```sh
man() {
  vim -c "ViewDocMan $1"
}
```
